name: Generate Compatibility Badges

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install hatch
          pip install -e .
      - name: Generate badges
        run: |
          python scripts/generate_compat_badges.py --output badges/
      - name: Commit and push badges
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add badges/
          git commit -m "chore: update compatibility badges" || echo "No changes"
          git push

